In [25]:
from sympy.matrices import Matrix 
import sympy as sp
import numpy as np
from Exercise import Exercise, MarkdownBlock

import math
import matplotlib.pyplot as plt
plt.rcParams.update({'font.size': 20})

from process_latex import process_sympy 

try:
    from config import URL, TOKEN
except:
    None

# TODO: replace with supplied strings
Exercise.URL = URL
Exercise.TOKEN = TOKEN

In [ ]:
m = r"What is $@a + @b$?"

params = {}
params["a"] = sp.Matrix(np.arange(4))
params["b"] = sp.Matrix(np.flip(np.arange(4)))

e = Exercise(MarkdownBlock(m, params))
e.add_answer(params["a"] + params["b"], True, "Correct!")
e.display()

e.write("vector_addition")
e.play()

In [ ]:
m = r"What is $@trace$?"

params = {}
params["trace"] = sp.Trace(sp.Matrix(np.arange(16).reshape((4,4))))

e = Exercise(MarkdownBlock(m, params))

ans = params["trace"].doit()

e.add_answer(ans, True, MarkdownBlock("Correct! $@trace$", params))
e.display()

e.write("trace")
e.play()

In [ ]:
m = r"What is $@inverse$?"

params = {}
params["inverse"] = sp.Inverse(sp.Matrix([[-1, 3/2], [1, -1]]))

e = Exercise(MarkdownBlock(m, params))

ans = params["inverse"].doit()
params["ans"] = ans

e.add_answer(ans, True, MarkdownBlock("Correct! $@inverse = @ans$", params))
e.add_default_feedback(MarkdownBlock("Correct! $@inverse = @ans$", params))
e.display()

e.write("inverse")
e.play()

In [ ]:
def generator():
    m = r"What is $@a + @b$?"
    
    params = {}
    params["a"] = np.random.randint(0, 10)
    params["b"] = np.random.randint(10, 20)
    params["ans"] = params["a"] + params["b"]

    e = Exercise(MarkdownBlock(m, params))
    e.add_answer(params["ans"], True, MarkdownBlock("Yes!", params))
    e.add_default_feedback(MarkdownBlock("No!", params))
    
    return e

Exercise.write_multiple(generator, 100, "int_param")

In [27]:
from sklearn.datasets import load_digits
digits = load_digits()

sorted_indices = np.argsort(digits.target)
nums = digits.images[sorted_indices]

In [100]:
def to_binary(array):
    return np.where(array > 7, 1, 0)

def show(array, filename, binary = True):
    data = to_binary(array) if binary else array 
    fig = plt.figure()
    plt.matshow(data, cmap='gray_r')
    plt.axis('off')
    plt.savefig("{}.png".format(filename), dpi=200, bbox_inches='tight')
    plt.close(fig)

# f, axarr = plt.subplots(1,10)
# unit = math.floor(len(nums)/10)
# start_offset = math.floor((1/2)*unit)
# for i in range(0, 10):
#     axarr[i].axis('off')
#     axarr[i].matshow(np.where(nums[start_offset + i*unit + 1] > 7, 1, 0), cmap="gray_r")

# plt.savefig("all_digits.png", dpi=500, bbox_inches='tight') 
# show(nums[7], "zero")
# show(nums[1500], "eight")

def matrix_to_image(matrix, filename, grid=True, values_in_cells=False, axis_indices=True, axis_titles=False):
    fig, ax = plt.subplots()
    
    if grid:
        # Minor ticks
        ax.set_xticks(np.arange(-.5, 10, 1), minor=True)
        ax.set_yticks(np.arange(-.5, 10, 1), minor=True)
        ax.grid(which='minor', color='black', linestyle='-', linewidth=2)
    else:
        plt.asix('off')
    
    if values_in_cells:
        import matplotlib.patheffects as pe
        for (i, j), z in np.ndenumerate(matrix):
            ax.text(j, i, '{}'.format(int(z)), ha='center', va='center', path_effects=[pe.withStroke(linewidth=4, foreground="white")]) 
        
    if axis_indices: 
        ax.set_xticklabels([i for i in range(0, 9)])
        ax.set_yticklabels([i for i in range(0, 9)])
        
    if axis_titles:
        ax.set_xlabel("column index")
        ax.xaxis.set_label_position('top')

        ax.set_ylabel("row index")
        ax.yaxis.set_label_position('left') 

    ax.matshow(matrix, cmap='gray_r')
    
    plt.savefig("{}.png".format(filename), dpi=200, bbox_inches='tight')
    plt.close(fig)

In [101]:
m = """
Given the matrices

<div class="d-flex flex-1 flex-items-center">
$A = $ <img src="a.png" height="150">, $B = $ <img src="b.png" height="150">
</div>

#### Task
Frist, determine $D = |A - B|$, then compute $\sum_{i=1}^{} \sum_{j=1}{} d_{i,j}$
"""

f1 = """
Correct!

$D = $ <img src="d.png" height="150"> 

$\sum D = @sum$
""" 

f2 = """
<div class="d-flex flex-1 flex-items-center">
Hint: $D = $ <img src="d.png" height="150"> 
</div>
""" 
def generator():
    # to vector: .reshape(-1, 1)
    a = to_binary(nums[np.random.randint(1700)])
    b = to_binary(nums[np.random.randint(1700)])
    d = np.abs(a-b)
    matrix_to_image(a, "a", grid=True, values_in_cells=True, axis_indices=True)
    matrix_to_image(b, "b", grid=True, values_in_cells=True, axis_indices=True)
    matrix_to_image(d, "d", grid=True, values_in_cells=True, axis_indices=True)
    
    e = Exercise(m)
    
    ans = int(np.sum(d))
    e.add_answer(expression=ans, correct=True, feedback=MarkdownBlock(md=f1, params=dict(sum=ans)))
    e.add_answer(expression=ans-1, correct=False, feedback="You are close, please check your answer")
    e.add_answer(expression=ans+1, correct=False, feedback="You are close, please check your answer")
    e.add_default_feedback(feedback=f2)
    return e

Exercise.write_multiple(generator, 10, "digit_vectors")

<ipython-input-100-e4d1973caad0>:40: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels([i for i in range(0, 9)])
<ipython-input-100-e4d1973caad0>:41: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_yticklabels([i for i in range(0, 9)])


In [95]:
m = """
Given the matrices

<div class="d-flex flex-1 flex-items-center">
$A = $ <img src="a.png" height="200">, $B = $ <img src="b.png" height="200">
</div>

#### Task
Frist, determine $D = |A - B|$, compute $\sum_{j=1}{} d_{1,j}$
"""

f1 = """
Correct!

$D = $ <img src="d.png" height="200"> 

$\sum D = @sum$
""" 

f2 = """
<div class="d-flex flex-1 flex-items-center">
Hint: $D = $ <img src="d.png" height="200"> 
</div>
""" 
def generator():
    # to vector: .reshape(-1, 1)
    a = nums[np.random.randint(1700)]
    b = nums[np.random.randint(1700)]
    d = np.abs(a-b)
    matrix_to_image(a, "a", grid=True, values_in_cells=True, axis_indices=True)
    matrix_to_image(b, "b", grid=True, values_in_cells=True, axis_indices=True)
    matrix_to_image(d, "d", grid=True, values_in_cells=True, axis_indices=True)
    
    e = Exercise(m)
    
    ans = np.sum(d[0,:])
    e.add_answer(expression=ans, correct=True, feedback=MarkdownBlock(md=f1, params=dict(sum=ans)))
    e.add_default_feedback(feedback=f2)
    return e

Exercise.write_multiple(generator, 5, "digit_vectors_grayscale")

<ipython-input-92-8f890e6fafea>:42: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels([i for i in range(0, 9)])
<ipython-input-92-8f890e6fafea>:43: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_yticklabels([i for i in range(0, 9)])


In [ ]:
import matplotlib.patheffects as pe
def values_in_matrix(ax, array):
    for (i, j), z in np.ndenumerate(array):
        ax.text(j, i, '{}'.format(int(z)), ha='center', va='center', path_effects=[pe.withStroke(linewidth=4, foreground="white")])

from scipy import ndimage, misc
import matplotlib.pyplot as plt
fig = plt.figure(figsize=(10, 10))
# plt.gray()  # show the filtered result in grayscale
ax1 = fig.add_subplot(121)  # left side
ax2 = fig.add_subplot(122)  # right side
ascent = to_binary(nums[516])
result = ndimage.sobel(ascent, mode="constant", cval=0.5)
values_in_matrix(ax1, ascent)
values_in_matrix(ax2, result)
print(type(result))
ax1.imshow(ascent)
ax2.imshow(result)

plt.show()

In [58]:
Exercise(r"What is $\begin{bmatrix} 1 \\ 2 \end{bmatrix} + \begin{bmatrix} 3 \\ 4 \end{bmatrix}$").play()

Published succesfully, preview at: https://www.mscthesis.nl/preview?id=954a2a9d-d6c3-4412-b511-89bb47daae41


In [23]:
v1 = sp.randMatrix(r=4, c=1, min=0, max=10)
sp.latex(v1)
f"Hello {v1}"

'Hello Matrix([[2], [5], [8], [3]])'

In [79]:
m = """
Place the following values at the right positions in a vector: $a_{@i2} = @v2, a_{@i3} = @v3, a_{@i4} = @v4, a_{@i1} = @v1$
"""
def generator():
    params = {}
    ans = np.zeros((4, 1), dtype=int)
    print(ans)
    for i in range(1, 5):
        params[f"i{str(i)}"] = i
        value = np.random.randint(0, 20)
        params[f"v{str(i)}"] = value
        ans[i-1,0] = value

    e = Exercise(MarkdownBlock(m, params))
    ans = sp.Matrix(np.array(ans).reshape(-1, 1))
    print(ans)
    e.add_answer(ans, True, "Indeed")
    return e

Exercise.write_multiple(generator, 10, "values_in_vector")



[[0]
 [0]
 [0]
 [0]]
Matrix([[7], [9], [9], [10]])
[[0]
 [0]
 [0]
 [0]]
Matrix([[4], [12], [8], [0]])
[[0]
 [0]
 [0]
 [0]]
Matrix([[10], [17], [8], [17]])
[[0]
 [0]
 [0]
 [0]]
Matrix([[7], [2], [2], [14]])
[[0]
 [0]
 [0]
 [0]]
Matrix([[13], [14], [16], [4]])
[[0]
 [0]
 [0]
 [0]]
Matrix([[2], [3], [18], [4]])
[[0]
 [0]
 [0]
 [0]]
Matrix([[5], [7], [5], [14]])
[[0]
 [0]
 [0]
 [0]]
Matrix([[2], [5], [12], [5]])
[[0]
 [0]
 [0]
 [0]]
Matrix([[1], [15], [4], [14]])
[[0]
 [0]
 [0]
 [0]]
Matrix([[16], [2], [19], [13]])


In [ ]:
# How many rows, how many columns (dimensions), how many total entries,
# Apply this function to each of the elements
# Value of single entry, constructing a matrix from other matrices, sum of multiple entries, square matrix, identity matrix, trace? 

In [118]:
m = """
Consider the matrix $A$, what is the value at $a_{@i, @j}$?
<p align="center">
$A = @a$
</p>
"""

def generator():
    params = {}
    rows = np.random.randint(2, 10)
    columns = np.random.randint(2, 10)
    matrix = sp.randMatrix(rows, columns)
    params["a"] = matrix 
    i = np.random.randint(0, rows)
    j = np.random.randint(0, columns)
    params["i"] = i + 1
    params["j"] = j + 1

    e = Exercise(MarkdownBlock(m, params))
    e.add_answer(sp.simplify(matrix[i,j]), True, "Correct!")
    if i < columns and j < rows:
        e.add_answer(sp.simplify(matrix[j,i]), False, "🤔 You seem to have swapped the row and column index.")
    return e
    
Exercise.write_multiple(generator, 100, "matrix_indexing")

In [130]:
m = """
Consider the matrix $A$, how many rows does $A$ have?
<p align="center">
$A = @a$
</p>
"""

def generator():
    params = {}
    rows = np.random.randint(2, 10)
    columns = np.random.randint(2, 10)
    matrix = sp.randMatrix(rows, columns)
    params["a"] = matrix 

    e = Exercise(MarkdownBlock(m, params))
    e.add_answer(sp.simplify(rows), True, "Correct!")
    if columns >= rows:
        e.add_answer(sp.simplify(columns), False, "🤔 Nope, that's the amount of columns.")
    return e
    
Exercise.write_multiple(generator, 100, "matrix_rows")

In [138]:
m = """
Consider the matrix $A$, how many values does $A$ contain?
<p align="center">
$A = @a$
</p>
"""

def generator():
    params = {}
    rows = np.random.randint(1, 10)
    columns = np.random.randint(1, 10)
    matrix = sp.randMatrix(rows, columns)
    params["a"] = matrix 
    ans = rows * columns
    params["ans"] = ans
    params["i"] = rows
    params["j"] = columns

    e = Exercise(MarkdownBlock(m, params))
    e.add_answer(sp.simplify(rows*columns), True, MarkdownBlock("Correct! The matrix has $@i$ rows and $@j$ columns, $@i \cdot @j = @ans$ values", params))
    e.add_default_feedback(MarkdownBlock("Hint: The matrix has $@i$ rows and $@j$ columns.", params))
    return e
    
Exercise.write_multiple(generator, 100, "matrix_entries")

In [216]:
from helpers import *
import random

m = r"""
Place the following values at the right positions in a matrix: ${values}$

$@s$
"""
def generator():
    params = {}
    character = "a"
    rows = np.random.randint(1,5)
    columns = np.random.randint(1,5)
    araw = [[[Symbol(f"{{{character}}}_{{{i+1}, {j+1}}}"), 5] for j in range(columns)] for i in range(rows)]
    for r in araw:
        random.shuffle(r)
    random.shuffle(araw)
    a = sp.Matrix(araw)
    #a = symbolic_matrix("a", 2, 3)
    #a = np.random.shuffle(np.array(a).astype(Symbol))
#     s = sp.Matrix(a) 
    params["a"] = a 
    params["s"] = a 
    
    v = ""
    for i, row in enumerate(araw):
        for j, col in enumerate(row):
            print(col)
            #index = f"@index{i}{j}"
            #value = f"@value{i}{j}"
            v = v + f"{latex(col[0])} = {col[1]}, " 
            #params[index] = col[0] 
            #params[value] = col[1] 
    
    # remove trailing space (latex wrapping should be tight e.g. $a,$ instead of $a, $) and comma ($a$ instead of $a,$)
    v = v[:-2]
    print(v)
    e = Exercise(MarkdownBlock(m.format(values=v), params))
    e.add_answer(0, True, "Indeed")
    return e

Exercise.write_multiple(generator, 10, "values_in_matrix")

[{a}_{2, 2}, 5]
[{a}_{2, 3}, 5]
[{a}_{2, 1}, 5]
[{a}_{3, 3}, 5]
[{a}_{3, 2}, 5]
[{a}_{3, 1}, 5]
[{a}_{1, 3}, 5]
[{a}_{1, 2}, 5]
[{a}_{1, 1}, 5]
{a}_{2, 2} = 5, {a}_{2, 3} = 5, {a}_{2, 1} = 5, {a}_{3, 3} = 5, {a}_{3, 2} = 5, {a}_{3, 1} = 5, {a}_{1, 3} = 5, {a}_{1, 2} = 5, {a}_{1, 1} = 5
[{a}_{1, 1}, 5]
[{a}_{1, 2}, 5]
[{a}_{2, 2}, 5]
[{a}_{2, 1}, 5]
{a}_{1, 1} = 5, {a}_{1, 2} = 5, {a}_{2, 2} = 5, {a}_{2, 1} = 5
[{a}_{1, 2}, 5]
[{a}_{1, 1}, 5]
[{a}_{3, 2}, 5]
[{a}_{3, 1}, 5]
[{a}_{2, 1}, 5]
[{a}_{2, 2}, 5]
{a}_{1, 2} = 5, {a}_{1, 1} = 5, {a}_{3, 2} = 5, {a}_{3, 1} = 5, {a}_{2, 1} = 5, {a}_{2, 2} = 5
[{a}_{1, 1}, 5]
[{a}_{1, 2}, 5]
[{a}_{2, 1}, 5]
[{a}_{2, 2}, 5]
[{a}_{3, 1}, 5]
[{a}_{3, 2}, 5]
{a}_{1, 1} = 5, {a}_{1, 2} = 5, {a}_{2, 1} = 5, {a}_{2, 2} = 5, {a}_{3, 1} = 5, {a}_{3, 2} = 5
[{a}_{1, 2}, 5]
[{a}_{1, 3}, 5]
[{a}_{1, 4}, 5]
[{a}_{1, 1}, 5]
[{a}_{2, 1}, 5]
[{a}_{2, 3}, 5]
[{a}_{2, 4}, 5]
[{a}_{2, 2}, 5]
[{a}_{3, 2}, 5]
[{a}_{3, 4}, 5]
[{a}_{3, 3}, 5]
[{a}_{3, 1}, 5]
{a}_{1, 2} =

In [199]:
sp.latex?

Signature:      
sp.latex(
    expr,
    *,
    full_prec=False,
    fold_frac_powers=False,
    fold_func_brackets=False,
    fold_short_frac=None,
    inv_trig_style='abbreviated',
    itex=False,
    ln_notation=False,
    long_frac_ratio=None,
    mat_delim='[',
    mat_str=None,
    mode='plain',
    mul_symbol=None,
    order=None,
    symbol_names={},
    root_notation=True,
    mat_symbol_style='plain',
    imaginary_unit='i',
    gothic_re_im=False,
    decimal_separator='period',
    perm_cyclic=True,
    parenthesize_super=True,
    min=None,
    max=None,
)
Call signature:  sp.latex(*args, **kwargs)
Type:            _PrintFunction
String form:     <function latex at 0x113497ee0>
File:            ~/Projects/exercise_public/exercise/lib/python3.9/site-packages/sympy/printing/latex.py
Docstring:      
Convert the given expression to LaTeX string representation.

Parameters
full_prec: boolean, optional
    If set to True, a floating point number is printed with full precision.
