In [1]:
from Exercise import Exercise, MarkdownBlock
from config import URL, TOKEN
import json

import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
import pandas as pd
plt.rcParams.update({'font.size': 20})

from sklearn.datasets import load_digits
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


Exercise.URL = URL
Exercise.TOKEN = TOKEN

In [31]:
from sympy import Rational, Symbol, latex, UnevaluatedExpr

u = lambda x : UnevaluatedExpr(x)

# Helper functions
def explain_add(a, b):
    assert(np.shape(a) == np.shape(b))
    rows, columns = np.shape(a)
    return sp.Matrix([[Symbol(f"({latex(u(a[i,j]))} + {latex(u(b[i,j]))})") for j in range(columns)] for i in range(rows)])

def symbolic_matrix(character, rows, columns):
    return sp.Matrix([[Symbol(f"{{{character}}}_{{{i+1}, {j+1}}}") for j in range(columns)] for i in range(rows)])

In [32]:
a = np.arange(4)
b = -1 * np.arange(1, 5)
a = sp.Matrix(a)
b = sp.Matrix(b)

s = "What is $@a + @b?$"

params = {}
params["a"] = a
params["b"] = b
e = Exercise(MarkdownBlock(s, params))

e.display()

s1 = "Yes, $@a + @b = @c = @d$!"

params["c"] = explain_add(a,b)
params["d"] = a + b
e.add_answer(a + b, True, MarkdownBlock(s1, params))
e.evaluate_answer(params["d"])

e.x = symbolic_matrix("a", 4,1)
e.y = symbolic_matrix("b", 4,1)
e.z = explain_add(e.x, e.y)
default_feedback = "Remember the definition of matrix addition: $@x + @y = @z$"
e.add_default_feedback(MarkdownBlock(default_feedback, vars(e)))
e.evaluate_answer(1)

e.write()
# e.publish()

In [45]:

    

s = "What is $@a \cdot @b$"

rows = np.random.randint(1, 6)
columns = np.random.randint(1, 6)

params = {}
params["a"] = sp.Matrix(np.random.randint(5, size=rows*columns).reshape((rows,columns)))
params["b"] = sp.Matrix(np.random.randint(5, size=(2+rows)*columns).reshape((columns,rows+2)))

e = Exercise(MarkdownBlock(s, params))

ans = params["a"] * params["b"]
display(ans)
e.add_answer(params["a"] * params["b"], True, "That's right!")
# e.add_default_feedback("Remember the definition of matrix multiplication: $@x \codot @y = @z$")


e.display()
e.write()
e.publish()

Matrix([
[12, 0, 9, 12, 6, 9, 0],
[ 8, 0, 6,  8, 4, 6, 0],
[ 4, 0, 3,  4, 2, 3, 0],
[ 4, 0, 3,  4, 2, 3, 0],
[ 4, 0, 3,  4, 2, 3, 0]])

Published succesfully, preview at: https://www.mscthesis.nl/preview?id=b3d89d7c-82d9-4b49-aa36-33ff390efeff


In [62]:
def explain_multiply(a, b):
    # #rows in b == #columns in a
    assert(np.shape(a)[1] == np.shape(b)[0])
    rows = np.shape(a)[0]
    columns = np.shape(b)[1]
    result = np.empty(shape=(rows, columns), dtype=object)
    for i in range(rows):
        row = a[i,:]
        for j in range(columns):
            column = b[:,j]
#             print(row)
#             print(column)
            zipped = zip(row, column)
            mapped = map(lambda t: Symbol(f"{latex(u(t[0]))} \cdot {latex(u(t[1]))}"), zipped)
            result[i, j] = list(mapped)
                
    return sp.Matrix(result)

a = np.arange(10).reshape((5,2))
b = np.arange(10).reshape((2,5))
print(a)
print(b)
print(a.dot(b))

display(explain_multiply(a, b))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[  5   6   7   8   9]
 [ 15  20  25  30  35]
 [ 25  34  43  52  61]
 [ 35  48  61  74  87]
 [ 45  62  79  96 113]]
[0 1]
[0 5]
[0 1]
[1 6]
[0 1]
[2 7]
[0 1]
[3 8]
[0 1]
[4 9]
[2 3]
[0 5]
[2 3]
[1 6]
[2 3]
[2 7]
[2 3]
[3 8]
[2 3]
[4 9]
[4 5]
[0 5]
[4 5]
[1 6]
[4 5]
[2 7]
[4 5]
[3 8]
[4 5]
[4 9]
[6 7]
[0 5]
[6 7]
[1 6]
[6 7]
[2 7]
[6 7]
[3 8]
[6 7]
[4 9]
[8 9]
[0 5]
[8 9]
[1 6]
[8 9]
[2 7]
[8 9]
[3 8]
[8 9]
[4 9]


Matrix([
[[0 \cdot 0, 1 \cdot 5], [0 \cdot 1, 1 \cdot 6], [0 \cdot 2, 1 \cdot 7], [0 \cdot 3, 1 \cdot 8], [0 \cdot 4, 1 \cdot 9]],
[[2 \cdot 0, 3 \cdot 5], [2 \cdot 1, 3 \cdot 6], [2 \cdot 2, 3 \cdot 7], [2 \cdot 3, 3 \cdot 8], [2 \cdot 4, 3 \cdot 9]],
[[4 \cdot 0, 5 \cdot 5], [4 \cdot 1, 5 \cdot 6], [4 \cdot 2, 5 \cdot 7], [4 \cdot 3, 5 \cdot 8], [4 \cdot 4, 5 \cdot 9]],
[[6 \cdot 0, 7 \cdot 5], [6 \cdot 1, 7 \cdot 6], [6 \cdot 2, 7 \cdot 7], [6 \cdot 3, 7 \cdot 8], [6 \cdot 4, 7 \cdot 9]],
[[8 \cdot 0, 9 \cdot 5], [8 \cdot 1, 9 \cdot 6], [8 \cdot 2, 9 \cdot 7], [8 \cdot 3, 9 \cdot 8], [8 \cdot 4, 9 \cdot 9]]])